---
- name: Configure Server and Deploy MoMoSim
  hosts: momosim
  become: true

  vars:
    repo_url: "https://github.com/kol-apo/Fintech---Formative-1-.git"
    app_dir: "/opt/momosim"

  tasks:
    - name: Install required system packages
      apt:
        name:
          - git
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone application repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Run docker compose
      command: docker compose up -d --build
      args:
        chdir: "{{ app_dir }}"

    - name: UFW - Allow port 22 (SSH)
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: UFW - Allow port 3000 (App)
      ufw:
        rule: allow
        port: '3000'
        proto: tcp

    - name: UFW - Enable firewall with default deny
      ufw:
        state: enabled
        policy: deny

    - name: Hardening - Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Hardening - Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted